// this file is for user of Genesis
#pragma once
#include "core/application.h"
#include "core/events/event.h"
#include "core/imgui/imgui_layer.h"
#include "core/input.h"
#include "core/layer/layer.h"
#include "core/layer/layer_stack.h"
#include "core/log/log.h"

#include "core/profile/profile_timer.h"
#include "core/renderer/buffer.h"
#include "core/renderer/camera/orthographic_camera_controller.h"
#include "core/renderer/camera/perspective_camera.h"
#include "core/renderer/render_command.h"
#include "core/renderer/renderer.h"
#include "core/renderer/renderer_2d.h"
#include "core/renderer/shader.h"
#include "core/renderer/shader_library.h"
#include "core/renderer/texture.h"
#include "core/renderer/vertex_array.h"
#include "core/time_step.h"
#include "core/timer.h"
